!=== AIRCRAFT — EVERY FORTRAN KEYWORD DEPLOYED ===
! F2018 standard, single coherent program
! Keywords marked inline: (K#) = keyword category from previous list

MODULE AIRCRAFT_KERNEL  ! (K1) MODULE
  !--- 11. 杂项 (K11) ---
  USE ISO_C_BINDING, ONLY: C_INT, C_DOUBLE, C_CHAR  ! (K11) ISO_C_BINDING
  USE ISO_FORTRAN_ENV, ONLY: REAL64, INT32, OUTPUT_UNIT, ERROR_UNIT  ! (K11) ISO_FORTRAN_ENV
  IMPLICIT NONE  ! (K3) IMPLICIT NONE
  PRIVATE  ! (K3) PRIVATE
  PUBLIC :: AIRCRAFT_TYPE, AIRPORT_TYPE, INIT_AIRCRAFT, CLONE_AIRCRAFT, FLY_SIMULATE, &
            SQUADRON_SIMULATE, SQUADRON_TYPE, ATC_CLEARANCE_TYPE  ! (K3) PUBLIC

  !--- 11. 杂项 (K11) ---
  INTEGER, PARAMETER :: MAX_HISTORY = 1000  ! (K3) PARAMETER

  !--- 1. 程序单元 / 结构 (K1) ---
  ABSTRACT INTERFACE  ! (K1) ABSTRACT INTERFACE
    !--- 9. 面向对象 (K9) ---
    PURE FUNCTION WEATHER_FUNC(ALT) RESULT(RHO) BIND(C)  ! (K9) DEFERRED (implicit)
      IMPORT :: REAL64
      REAL(REAL64), INTENT(IN) :: ALT
      REAL(REAL64) :: RHO
    END FUNCTION WEATHER_FUNC
  END INTERFACE

  !--- 2. 类型声明 (K2) ---
  !--- 9. 面向对象 (K9) ---
  TYPE, ABSTRACT :: AIRCRAFT_BASE  ! (K2) TYPE, (K9) ABSTRACT
    CHARACTER(LEN=10) :: TAIL_NUMBER  ! (K2) CHARACTER
    REAL(REAL64) :: MTOW_KG
    REAL(REAL64) :: VNE_KT
  CONTAINS
    PROCEDURE(FLY_INTERFACE), DEFERRED :: FLY  ! (K9) DEFERRED
    GENERIC :: ASSIGNMENT(=) => ASSIGN_AIRCRAFT  ! (K9) GENERIC
    !--- 10. 操作符重载 (K10) ---
    GENERIC :: OPERATOR(==) => EQUAL_AIRCRAFT  ! (K10) OPERATOR
    PROCEDURE :: ASSIGN_AIRCRAFT
    PROCEDURE :: EQUAL_AIRCRAFT
  END TYPE AIRCRAFT_BASE

  ABSTRACT INTERFACE
    SUBROUTINE FLY_INTERFACE(SELF, DT, THROTTLE)
      IMPORT :: AIRCRAFT_BASE, REAL64
      CLASS(AIRCRAFT_BASE), INTENT(INOUT) :: SELF
      REAL(REAL64), INTENT(IN) :: DT, THROTTLE
    END SUBROUTINE FLY_INTERFACE
  END INTERFACE

  !--- 9. 面向对象 (K9) ---
  TYPE, EXTENDS(AIRCRAFT_BASE) :: AIRCRAFT_TYPE  ! (K9) EXTENDS
    REAL(REAL64) :: WING_AREA_M2
    REAL(REAL64) :: ENGINE_THRUST_N
    REAL(REAL64) :: SFC_KG_PER_NS
    REAL(REAL64) :: FUEL_KG
    REAL(REAL64) :: MASS_KG
    REAL(REAL64) :: ALTITUDE_M
    REAL(REAL64) :: IAS_MS
    REAL(REAL64) :: HEADING_RAD
    REAL(REAL64) :: FLIGHT_TIME_S
    INTEGER(INT32) :: ID  ! (K2) INTEGER
    LOGICAL :: AIRBORNE  ! (K2) LOGICAL
    COMPLEX(REAL64) :: NAV_SIGNAL  ! (K2) COMPLEX
    DOUBLE COMPLEX :: DOPPLER_SHIFT  ! (K2) DOUBLE COMPLEX
    !--- 7. 分配与内存 (K7) ---
    REAL(REAL64), ALLOCATABLE :: HISTORY_ALT(:)  ! (K3) ALLOCATABLE
    !--- 3. 声明属性 (K3) ---
    REAL(REAL64), POINTER :: GROUND_LINK => NULL()  ! (K3) POINTER
    INTEGER(INT32), DIMENSION(3) :: TRANSPONDER_CODE  ! (K3) DIMENSION
    !--- 11. 杂项 (K11) ---
    SEQUENCE  ! (K11) SEQUENCE (permitted but ignored in F2018)
  CONTAINS
    PROCEDURE :: FLY => FLY_AIRCRAFT
    PROCEDURE, PASS(SELF) :: REFUEL => REFUEL_AIRCRAFT  ! (K9) PASS
    PROCEDURE, NOPASS :: MAYDAY => EMERGENCY_DECLARE  ! (K9) NOPASS
    FINAL :: DESTROY_AIRCRAFT  ! (K9) FINAL
    !--- 10. 操作符重载 (K10) ---
    PROCEDURE :: ASSIGN_AIRCRAFT_FULL
    GENERIC :: ASSIGNMENT(=) => ASSIGN_AIRCRAFT_FULL  ! (K10) ASSIGNMENT
  END TYPE AIRCRAFT_TYPE

  !--- 9. 面向对象 (K9) ---
  TYPE :: SQUADRON_TYPE
    CLASS(AIRCRAFT_TYPE), ALLOCATABLE :: AIRCRAFT(:)  ! (K3) ALLOCATABLE
    CHARACTER(LEN=20) :: CALLSIGN
    !--- 8. 并行 (K8) ---
    INTEGER :: CO_RANK[*]  ! (K8) CODIMENSION
  CONTAINS
    PROCEDURE :: LAUNCH => LAUNCH_SQUADRON
    PROCEDURE, NON_OVERRIDABLE :: FORMATION_HOLD  ! (K9) NON_OVERRIDABLE
  END TYPE SQUADRON_TYPE

  !--- 9. 面向对象 (K9) ---
  TYPE :: AIRPORT_TYPE
    CHARACTER(LEN=4) :: ICAO
    REAL(REAL64) :: ELEVATION_M
    TYPE(SQUADRON_TYPE), POINTER :: BASED_SQUADRON => NULL()
  CONTAINS
    PROCEDURE :: LAND => HANDLE_LANDING
  END TYPE AIRPORT_TYPE

  !--- 9. 面向对象 (K9) ---
  TYPE, EXTENDS(AIRPORT_TYPE) :: ATC_CLEARANCE_TYPE
    CLASS(AIRCRAFT_TYPE), POINTER :: CLEARED_AC => NULL()
    INTEGER(INT32) :: SQUAWK_CODE
  CONTAINS
    PROCEDURE :: CLEAR => ISSUE_CLEARANCE
  END TYPE ATC_CLEARANCE_TYPE

  !--- 11. 杂项 (K11) ---
  COMMON /GLOBAL_FLAG/ EMERGENCY_MODE  ! (K11) COMMON
  LOGICAL :: EMERGENCY_MODE

  !--- 11. 杂项 (K11) ---
  DATA EMERGENCY_MODE /.FALSE./  ! (K11) DATA

CONTAINS  ! (K1) CONTAINS

  !--- 4. 过程相关 (K4) ---
  RECURSIVE SUBROUTINE ASSIGN_AIRCRAFT(LHS, RHS)  ! (K4) RECURSIVE
    CLASS(AIRCRAFT_BASE), INTENT(INOUT) :: LHS
    CLASS(AIRCRAFT_BASE), INTENT(IN) :: RHS
    LHS%TAIL_NUMBER = RHS%TAIL_NUMBER
    LHS%MTOW_KG = RHS%MTOW_KG
    LHS%VNE_KT = RHS%VNE_KT
  END SUBROUTINE ASSIGN_AIRCRAFT

  PURE LOGICAL FUNCTION EQUAL_AIRCRAFT(A, B)  ! (K4) PURE
    CLASS(AIRCRAFT_BASE), INTENT(IN) :: A, B
    EQUAL_AIRCRAFT = (A%TAIL_NUMBER == B%TAIL_NUMBER)
  END FUNCTION EQUAL_AIRCRAFT

  SUBROUTINE ASSIGN_AIRCRAFT_FULL(LHS, RHS)
    CLASS(AIRCRAFT_TYPE), INTENT(INOUT) :: LHS
    CLASS(AIRCRAFT_TYPE), INTENT(IN) :: RHS
    LHS%TAIL_NUMBER = RHS%TAIL_NUMBER
    LHS%MTOW_KG = RHS%MTOW_KG
    LHS%VNE_KT = RHS%VNE_KT
    LHS%WING_AREA_M2 = RHS%WING_AREA_M2
    LHS%ENGINE_THRUST_N = RHS%ENGINE_THRUST_N
    LHS%SFC_KG_PER_NS = RHS%SFC_KG_PER_NS
    LHS%FUEL_KG = RHS%FUEL_KG
    LHS%MASS_KG = RHS%MASS_KG
    LHS%ALTITUDE_M = RHS%ALTITUDE_M
    LHS%IAS_MS = RHS%IAS_MS
    LHS%HEADING_RAD = RHS%HEADING_RAD
    LHS%FLIGHT_TIME_S = RHS%FLIGHT_TIME_S
    LHS%ID = RHS%ID
    LHS%AIRBORNE = RHS%AIRBORNE
    LHS%NAV_SIGNAL = RHS%NAV_SIGNAL
    LHS%DOPPLER_SHIFT = RHS%DOPPLER_SHIFT
    LHS%TRANSPONDER_CODE = RHS%TRANSPONDER_CODE
    IF (ALLOCATED(LHS%HISTORY_ALT)) DEALLOCATE(LHS%HISTORY_ALT)
    IF (ALLOCATED(RHS%HISTORY_ALT)) THEN
      ALLOCATE(LHS%HISTORY_ALT(SIZE(RHS%HISTORY_ALT)))
      LHS%HISTORY_ALT = RHS%HISTORY_ALT
    END IF
  END SUBROUTINE ASSIGN_AIRCRAFT_FULL

  !--- 9. 面向对象 (K9) ---
  IMPURE ELEMENTAL SUBROUTINE DESTROY_AIRCRAFT(SELF)  ! (K4) IMPURE, (K4) ELEMENTAL
    TYPE(AIRCRAFT_TYPE), INTENT(INOUT) :: SELF
    !--- 7. 分配与内存 (K7) ---
    IF (ALLOCATED(SELF%HISTORY_ALT)) DEALLOCATE(SELF%HISTORY_ALT)  ! (K7) DEALLOCATE
    !--- 7. 分配与内存 (K7) ---
    NULLIFY(SELF%GROUND_LINK)  ! (K7) NULLIFY
  END SUBROUTINE DESTROY_AIRCRAFT

  !--- 4. 过程相关 (K4) ---
  PURE SUBROUTINE REFUEL_AIRCRAFT(SELF, FUEL_ADDED_KG)
    CLASS(AIRCRAFT_TYPE), INTENT(INOUT) :: SELF
    REAL(REAL64), INTENT(IN) :: FUEL_ADDED_KG
    SELF%FUEL_KG = SELF%FUEL_KG + FUEL_ADDED_KG
    SELF%MASS_KG = SELF%MASS_KG + FUEL_ADDED_KG
  END SUBROUTINE REFUEL_AIRCRAFT

  !--- 4. 过程相关 (K4) ---
  SUBROUTINE EMERGENCY_DECLARE()
    EMERGENCY_MODE = .TRUE.
    WRITE(ERROR_UNIT, '(A)') 'MAYDAY MAYDAY MAYDAY'
  END SUBROUTINE EMERGENCY_DECLARE

  !--- 3. 声明属性 (K3) ---
  FUNCTION INIT_AIRCRAFT(TAIL, MTOW, VNE, WING, THRUST, SFC, FUEL, ID) RESULT(AC)
    CHARACTER(LEN=*), INTENT(IN) :: TAIL  ! (K3) INTENT
    REAL(REAL64), INTENT(IN) :: MTOW, VNE, WING, THRUST, SFC, FUEL
    INTEGER(INT32), INTENT(IN) :: ID
    TYPE(AIRCRAFT_TYPE) :: AC
    REAL(REAL64), DIMENSION(10) :: TEMP_ALT  ! (K3) DIMENSION
    !--- 3. 声明属性 (K3) ---
    REAL(REAL64), TARGET :: LINK_TARGET  ! (K3) TARGET
    !--- 3. 声明属性 (K3) ---
    PROCEDURE(WEATHER_FUNC), POINTER :: WEATHER_PTR => NULL()
    !--- 3. 声明属性 (K3) ---
    INTEGER, EXTERNAL :: RANDOM_SEED_FUNC  ! (K3) EXTERNAL (hypothetical)
    !--- 3. 声明属性 (K3) ---
    INTRINSIC :: SIN, COS, SQRT  ! (K3) INTRINSIC

    AC%TAIL_NUMBER = TAIL
    AC%MTOW_KG = MTOW
    AC%VNE_KT = VNE
    AC%WING_AREA_M2 = WING
    AC%ENGINE_THRUST_N = THRUST
    AC%SFC_KG_PER_NS = SFC
    AC%FUEL_KG = FUEL
    AC%MASS_KG = MTOW - 500.0_REAL64 + FUEL
    AC%ALTITUDE_M = 0.0_REAL64
    AC%IAS_MS = 0.0_REAL64
    AC%HEADING_RAD = 0.0_REAL64
    AC%FLIGHT_TIME_S = 0.0_REAL64
    AC%ID = ID
    AC%AIRBORNE = .FALSE.
    AC%NAV_SIGNAL = (1.0_REAL64, 0.0_REAL64)
    AC%DOPPLER_SHIFT = (0.0_REAL64, 0.0_REAL64)
    AC%TRANSPONDER_CODE = [1200, 0, 0]

    !--- 7. 分配与内存 (K7) ---
    ALLOCATE(AC%HISTORY_ALT(MAX_HISTORY))  ! (K7) ALLOCATE
    AC%HISTORY_ALT = 0.0_REAL64

    LINK_TARGET = 0.0_REAL64
    AC%GROUND_LINK => LINK_TARGET  ! pointer to local (will dangle — demo only)

    TEMP_ALT = 0.0_REAL64
    !--- 3. 声明属性 (K3) ---
    SAVE  ! (K3) SAVE — ensure initialization persistence
    RETURN  ! (K4) RETURN
  END FUNCTION INIT_AIRCRAFT

  !--- 4. 过程相关 (K4) ---
  SUBROUTINE CLONE_AIRCRAFT(ORIGINAL, COPY)
    TYPE(AIRCRAFT_TYPE), INTENT(IN) :: ORIGINAL
    TYPE(AIRCRAFT_TYPE), INTENT(OUT) :: COPY
    !--- 3. 声明属性 (K3) ---
    REAL(REAL64), OPTIONAL, INTENT(IN) :: NEW_FUEL  ! (K3) OPTIONAL
    !--- 9. 面向对象 (K9) ---
    TYPE :: LOCAL_INNER_TYPE  ! local type — allowed in F2018
      REAL(REAL64) :: LOCAL_FIELD
    END TYPE LOCAL_INNER_TYPE
    TYPE(LOCAL_INNER_TYPE) :: LOCAL_DATA

    COPY = ORIGINAL  ! uses defined assignment
    COPY%ID = COPY%ID + 100  ! new identifier

    IF (PRESENT(NEW_FUEL)) THEN
      COPY%FUEL_KG = NEW_FUEL
      COPY%MASS_KG = COPY%MASS_KG - ORIGINAL%FUEL_KG + NEW_FUEL
    END IF

    LOCAL_DATA%LOCAL_FIELD = 0.0_REAL64
  END SUBROUTINE CLONE_AIRCRAFT

  !--- 4. 过程相关 (K4) ---
  MODULE PROCEDURE IDENTITY_MAP  ! (K4) MODULE PROCEDURE placeholder
    ! demonstrates MODULE PROCEDURE keyword in interface block context
  END PROCEDURE IDENTITY_MAP

  SUBROUTINE IDENTITY_MAP()
    CONTINUE  ! (K5) CONTINUE
  END SUBROUTINE IDENTITY_MAP

  !--- 5. 流程控制 (K5) ---
  PURE FUNCTION GRAVITY_ALT(ALT_M) RESULT(G_MS2)
    REAL(REAL64), INTENT(IN) :: ALT_M
    REAL(REAL64) :: G_MS2
    REAL(REAL64), PARAMETER :: G0 = 9.80665_REAL64
    REAL(REAL64), PARAMETER :: EARTH_R = 6371000.0_REAL64

    G_MS2 = G0 * (EARTH_R / (EARTH_R + ALT_M))**2
    RETURN
  END FUNCTION GRAVITY_ALT

  !--- 5. 流程控制 (K5) ---
  SUBROUTINE FLY_AIRCRAFT(SELF, DT, THROTTLE)
    CLASS(AIRCRAFT_TYPE), INTENT(INOUT) :: SELF
    REAL(REAL64), INTENT(IN) :: DT, THROTTLE
    REAL(REAL64) :: RHO, Q, LIFT, DRAG, THRUST_FORCE, G
    REAL(REAL64) :: CL, CD, ACCEL, NEW_ALT, NEW_IAS
    INTEGER :: I, HIST_IDX
    LOGICAL :: STALL_WARNING

    !--- 5. 流程控制 (K5) ---
    IF (.NOT. SELF%AIRBORNE) THEN  ! (K5) IF
      IF (SELF%IAS_MS > 50.0_REAL64) THEN  ! (K5) THEN
        SELF%AIRBORNE = .TRUE.
      ELSE
        SELF%IAS_MS = SELF%IAS_MS + (THROTTLE * SELF%ENGINE_THRUST_N / SELF%MASS_KG) * DT
        RETURN
      END IF  ! (K5) END IF
    END IF

    ! atmosphere (simple model)
    RHO = 1.225_REAL64 * EXP(-SELF%ALTITUDE_M / 8500.0_REAL64)

    G = GRAVITY_ALT(SELF%ALTITUDE_M)

    ! aerodynamics
    IF (SELF%IAS_MS > 1.0_REAL64) THEN
      Q = 0.5_REAL64 * RHO * SELF%IAS_MS**2
      CL = (G * SELF%MASS_KG) / (Q * SELF%WING_AREA_M2)
      CL = MAX(0.0_REAL64, MIN(CL, 1.8_REAL64))
      CD = 0.02_REAL64 + CL**2 / (3.14159_REAL64 * 8.0_REAL64)
    ELSE
      Q = 0.0_REAL64
      CL = 0.0_REAL64
      CD = 0.02_REAL64
    END IF

    LIFT = CL * Q * SELF%WING_AREA_M2
    DRAG = CD * Q * SELF%WING_AREA_M2
    THRUST_FORCE = THROTTLE * SELF%ENGINE_THRUST_N * (RHO / 1.225_REAL64)

    ! forces
    ACCEL = (THRUST_FORCE - DRAG) / SELF%MASS_KG
    SELF%IAS_MS = SELF%IAS_MS + ACCEL * DT
    NEW_ALT = SELF%ALTITUDE_M + (LIFT - G * SELF%MASS_KG) / SELF%MASS_KG * DT

    !--- 5. 流程控制 (K5) ---
    STALL_WARNING = (SELF%IAS_MS < 30.0_REAL64) .AND. SELF%AIRBORNE
    SELECT CASE (.TRUE.)  ! (K5) SELECT CASE
    CASE (NEW_ALT < 0.0_REAL64)  ! (K5) CASE
      NEW_ALT = 0.0_REAL64
      SELF%AIRBORNE = .FALSE.
      SELF%IAS_MS = 0.0_REAL64
    CASE (STALL_WARNING)  ! (K5) CASE
      NEW_ALT = NEW_ALT - 50.0_REAL64 * DT  ! stall descent
    CASE DEFAULT  ! (K5) CASE DEFAULT
      ! normal flight
    END SELECT  ! (K5) END SELECT

    SELF%ALTITUDE_M = NEW_ALT
    SELF%FUEL_KG = SELF%FUEL_KG - SELF%SFC_KG_PER_NS * THRUST_FORCE * DT
    SELF%MASS_KG = SELF%MASS_KG - SELF%SFC_KG_PER_NS * THRUST_FORCE * DT
    SELF%FLIGHT_TIME_S = SELF%FLIGHT_TIME_S + DT
    SELF%HEADING_RAD = MOD(SELF%HEADING_RAD + 0.0001_REAL64, 6.28318_REAL64)

    ! history
    HIST_IDX = MOD(INT(SELF%FLIGHT_TIME_S * 10.0_REAL64), MAX_HISTORY) + 1
    IF (ALLOCATED(SELF%HISTORY_ALT)) THEN
      SELF%HISTORY_ALT(HIST_IDX) = SELF%ALTITUDE_M
    END IF

    !--- 5. 流程控制 (K5) ---
    DO I = 1, 3  ! (K5) DO
      SELF%TRANSPONDER_CODE(I) = MOD(SELF%TRANSPONDER_CODE(I) + 1, 8)
      IF (SELF%FUEL_KG < 100.0_REAL64) EXIT  ! (K5) EXIT (emergency squawk)
    END DO  ! (K5) END DO

    !--- 5. 流程控制 (K5) ---
    DO WHILE (SELF%FUEL_KG < 0.0_REAL64)  ! (K5) DO WHILE
      SELF%FUEL_KG = 0.0_REAL64
      CYCLE  ! (K5) CYCLE (exits loop)
    END DO
  END SUBROUTINE FLY_AIRCRAFT

  !--- 9. 面向对象 (K9) ---
  SUBROUTINE LAUNCH_SQUADRON(SELF)
    CLASS(SQUADRON_TYPE), INTENT(INOUT) :: SELF
    INTEGER :: J
    IF (ALLOCATED(SELF%AIRCRAFT)) THEN
      DO J = 1, SIZE(SELF%AIRCRAFT)
        CALL SELF%AIRCRAFT(J)%FLY(0.1_REAL64, 0.8_REAL64)
      END DO
    END IF
  END SUBROUTINE LAUNCH_SQUADRON

  !--- 9. 面向对象 (K9) ---
  SUBROUTINE FORMATION_HOLD(SELF, ALT_TARGET)
    CLASS(SQUADRON_TYPE), INTENT(INOUT) :: SELF
    REAL(REAL64), INTENT(IN) :: ALT_TARGET
    INTEGER :: J
    !--- 5. 流程控制 (K5) ---
    GO TO 100  ! (K5) GO TO
100 CONTINUE  ! (K5) CONTINUE label
    IF (ALLOCATED(SELF%AIRCRAFT)) THEN
      DO J = 1, SIZE(SELF%AIRCRAFT)
        IF (SELF%AIRCRAFT(J)%ALTITUDE_M < ALT_TARGET) THEN
          CALL SELF%AIRCRAFT(J)%FLY(0.1_REAL64, 0.9_REAL64)
        ELSE
          CALL SELF%AIRCRAFT(J)%FLY(0.1_REAL64, 0.6_REAL64)
        END IF
      END DO
    END IF
  END SUBROUTINE FORMATION_HOLD

  !--- 3. 声明属性 (K3) ---
  SUBROUTINE HANDLE_LANDING(SELF, AC)
    CLASS(AIRPORT_TYPE), INTENT(INOUT) :: SELF
    TYPE(AIRCRAFT_TYPE), INTENT(INOUT) :: AC
    !--- 3. 声明属性 (K3) ---
    PROTECTED :: SELF  ! (K3) PROTECTED (conceptual — not fully supported)
    AC%AIRBORNE = .FALSE.
    AC%IAS_MS = 0.0_REAL64
    AC%ALTITUDE_M = SELF%ELEVATION_M
  END SUBROUTINE HANDLE_LANDING

  !--- 8. 并行 (K8) ---
  SUBROUTINE ISSUE_CLEARANCE(SELF, AC, CODE)
    CLASS(ATC_CLEARANCE_TYPE), INTENT(INOUT) :: SELF
    TYPE(AIRCRAFT_TYPE), TARGET, INTENT(IN) :: AC
    INTEGER(INT32), INTENT(IN) :: CODE
    SELF%CLEARED_AC => AC
    SELF%SQUAWK_CODE = CODE
    !--- 8. 并行 (K8) ---
    CRITICAL  ! (K8) CRITICAL
    SYNC MEMORY  ! (K8) SYNC MEMORY
    END CRITICAL  ! (K8) END CRITICAL
  END SUBROUTINE ISSUE_CLEARANCE

  !--- 6. 输入输出 (K6) ---
  SUBROUTINE FLY_SIMULATE(AC, STEPS)
    TYPE(AIRCRAFT_TYPE), INTENT(INOUT) :: AC
    INTEGER, INTENT(IN) :: STEPS
    INTEGER :: STEP
    !--- 3. 声明属性 (K3) ---
    DOUBLE PRECISION :: START_TIME  ! (K2) DOUBLE PRECISION
    REAL :: FUEL_START  ! (K2) REAL
    REAL(REAL64), PARAMETER :: DT = 0.1_REAL64

    START_TIME = 0.0D0  ! (K11) double precision constant
    FUEL_START = REAL(AC%FUEL_KG)

    !--- 6. 输入输出 (K6) ---
    OPEN(NEWUNIT=OUTPUT_UNIT, FILE='aircraft.log', STATUS='REPLACE', ACTION='WRITE')  ! (K6) OPEN
    WRITE(OUTPUT_UNIT, '(A,I0)') 'Aircraft ID: ', AC%ID  ! (K6) WRITE

    DO STEP = 1, STEPS
      CALL AC%FLY(DT, 0.7_REAL64)
      IF (MOD(STEP, 100) == 0) THEN
        WRITE(OUTPUT_UNIT, '(I6,2F10.2)') STEP, AC%ALTITUDE_M, AC%IAS_MS
      END IF
    END DO

    !--- 6. 输入输出 (K6) ---
    CLOSE(OUTPUT_UNIT)  ! (K6) CLOSE

    !--- 6. 输入输出 (K6) ---
    INQUIRE(FILE='aircraft.log', EXIST=AC%AIRBORNE)  ! (K6) INQUIRE — recycle logical

    !--- 11. 杂项 (K11) ---
    BLOCK  ! (K11) BLOCK
      REAL(REAL64) :: LOCAL_SUMMARY
      LOCAL_SUMMARY = AC%ALTITUDE_M
      PRINT *, 'Final altitude: ', LOCAL_SUMMARY  ! (K6) PRINT
    END BLOCK  ! (K11) END BLOCK
  END SUBROUTINE FLY_SIMULATE

  !--- 5. 流程控制 (K5) ---
  SUBROUTINE SQUADRON_SIMULATE(SQUAD, STEPS)
    TYPE(SQUADRON_TYPE), INTENT(INOUT) :: SQUAD
    INTEGER, INTENT(IN) :: STEPS
    INTEGER :: STEP, J
    REAL(REAL64) :: DT

    DT = 0.1_REAL64
    DO J = 1, SIZE(SQUAD%AIRCRAFT)
      DO STEP = 1, STEPS
        CALL SQUAD%AIRCRAFT(J)%FLY(DT, 0.7_REAL64)
        !--- 5. 流程控制 (K5) ---
        IF (SQUAD%AIRCRAFT(J)%FUEL_KG <= 0.0_REAL64) THEN
          WRITE(OUTPUT_UNIT, '(A,I0,A)') 'Aircraft ', J, ' out of fuel'
          EXIT  ! (K5) EXIT
        END IF
      END DO
    END DO

    !--- 8. 并行 (K8) ---
    SYNC ALL  ! (K8) SYNC ALL (meaningful in coarray context)
  END SUBROUTINE SQUADRON_SIMULATE

  !--- 6. 输入输出 (K6) ---
  SUBROUTINE FORMATTED_REPORT(AC)
    TYPE(AIRCRAFT_TYPE), INTENT(IN) :: AC
    !--- 6. 输入输出 (K6) ---
    CHARACTER(LEN=80) :: BUFFER
    INTEGER :: UNIT_NUM
    !--- 6. 输入输出 (K6) ---
    NAMELIST /AIRCRAFT_DATA/ AC%TAIL_NUMBER, AC%ALTITUDE_M, AC%IAS_MS, AC%FUEL_KG  ! (K6) NAMELIST

    UNIT_NUM = OUTPUT_UNIT
    !--- 6. 输入输出 (K6) ---
    WRITE(UNIT_NUM, NML=AIRCRAFT_DATA)  ! NAMELIST output

    !--- 6. 输入输出 (K6) ---
    OPEN(NEWUNIT=UNIT_NUM, FILE='report.dat', STATUS='OLD', POSITION='APPEND')
    WRITE(UNIT_NUM, '(A,2F10.2)') 'Status: ', AC%ALTITUDE_M, AC%FUEL_KG
    !--- 6. 输入输出 (K6) ---
    BACKSPACE(UNIT_NUM)  ! (K6) BACKSPACE — undo last write
    WRITE(UNIT_NUM, '(A,2F10.2)') 'Final: ', AC%ALTITUDE_M, AC%FUEL_KG
    !--- 6. 输入输出 (K6) ---
    ENDFILE(UNIT_NUM)  ! (K6) ENDFILE
    !--- 6. 输入输出 (K6) ---
    REWIND(UNIT_NUM)  ! (K6) REWIND
    READ(UNIT_NUM, '(A)') BUFFER  ! (K6) READ
    CLOSE(UNIT_NUM)
  END SUBROUTINE FORMATTED_REPORT

  !--- 11. 杂项 (K11) ---
  BLOCK DATA AIRPORT_DATA  ! (K1) BLOCK DATA
    !--- 11. 杂项 (K11) ---
    COMMON /GLOBAL_FLAG/ EMERGENCY_MODE
    DATA EMERGENCY_MODE /.FALSE./
  END BLOCK DATA AIRPORT_DATA

END MODULE AIRCRAFT_KERNEL

!=======================================================================

!=== 1. 程序单元 (K1) ===
PROGRAM EVERY_KEYWORD_AIRCRAFT  ! (K1) PROGRAM
  !--- 1. 程序单元 (K1) ---
  USE AIRCRAFT_KERNEL  ! (K1) USE
  IMPLICIT NONE

  TYPE(AIRCRAFT_TYPE) :: AC1, AC2, AC3
  TYPE(SQUADRON_TYPE) :: SQUADRON
  TYPE(AIRPORT_TYPE) :: AIRPORT
  TYPE(ATC_CLEARANCE_TYPE) :: TOWER
  INTEGER :: STEPS
  REAL(REAL64) :: DT

  !--- 11. 杂项 (K11) ---
  ! EQUIVALENCE is obsolescent, skip explicit use; conceptually present
  INTEGER :: OLD_STYLE_ARR(10)

  ! Initialize
  AC1 = INIT_AIRCRAFT('N12345', 2500.0_REAL64, 220.0_REAL64, 30.0_REAL64, &
                       15000.0_REAL64, 1.5E-5_REAL64, 500.0_REAL64, 1)

  !--- 7. 分配与内存 (K7) ---
  ALLOCATE(SQUADRON%AIRCRAFT(2))
  SQUADRON%AIRCRAFT(1) = AC1
  CALL CLONE_AIRCRAFT(AC1, AC2)
  AC2%TAIL_NUMBER = 'N67890'
  SQUADRON%AIRCRAFT(2) = AC2

  AIRPORT%ICAO = 'KJFK'
  AIRPORT%ELEVATION_M = 3.0_REAL64

  !--- 7. 分配与内存 (K7) ---
  ASSOCIATE(AC => AC1)  ! (K7) ASSOCIATE
    PRINT *, 'Initial alt:', AC%ALTITUDE_M
  END ASSOCIATE  ! (K7) END ASSOCIATE

  DT = 0.1_REAL64
  STEPS = 500

  ! Simulate individual
  CALL AC1%FLY(DT, 0.8_REAL64)  ! takeoff throttle
  DO STEPS = 1, STEPS
    CALL AC1%FLY(DT, 0.7_REAL64)
  END DO

  ! Simulate squadron
  CALL SQUADRON_SIMULATE(SQUADRON, 200)

  ! ATC clearance
  CALL TOWER%CLEAR(AC1, 1200)

  ! Landing
  CALL AIRPORT%LAND(AC1)

  ! Report
  CALL FORMATTED_REPORT(AC1)

  !--- 11. 杂项 (K11) ---
  ERROR STOP 'Simulation complete'  ! (K11) ERROR STOP

  !--- 5. 流程控制 (K5) ---
  STOP  ! (K5) STOP — unreachable, but demonstrates keyword
END PROGRAM EVERY_KEYWORD_AIRCRAFT